name: Build

on:
  workflow_call:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: zed-industries/zed
      ref:
        description: Branch/tag/ref to build
        type: string
        required: true
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: zed-industries/zed
      ref:
        description: Branch/tag/ref to build
        type: string
        default: main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        backend: [vulkan, opengl]
        include:
          - backend: vulkan
            artifact_name: zed-release
            rustflags: ""
          - backend: opengl
            artifact_name: zed-release-opengl
            rustflags: "--cfg gles"
      fail-fast: false

    steps:
      - name: Enable long paths in Git
        run: |
          git config --system core.longpaths true

      - name: Enable long paths in Windows
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Install PSToml module
        shell: pwsh
        run: Install-Module -Name PSToml -Scope CurrentUser -Force

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout Zed
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: zed

      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasip1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.backend }}-${{ hashFiles('Cargo.lock') }}
          workspaces: "zed -> target"

      - name: Setup rustflags
        shell: pwsh
        run: ./scripts/Parse-Rustflags.ps1 ${{ matrix.rustflags }}

      - name: Install zigbuild
        working-directory: zed
        run: cargo install --locked cargo-zigbuild
        
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wget_release_id: latest

      - name: Install zig
        run: winget install -e --id zig.zig
        
      - name: Build release
        working-directory: zed
        env:
          ZED_UPDATE_EXPLANATION: "Please use Scoop to update Zed."
          ZED_BUILD_REMOTE_SERVER: "zigbuild nocompress"
        run: cargo build --release

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: zed/target/release/zed.exe
